---
title: "R Notebook"
output: html_notebook
from: http://curleylab.psych.columbia.edu/nba.html
---
```{r}
# Import libraries
library(RCurl)
library(jsonlite)
library(dplyr)
library(sp)
library(ggplot2)
library(data.table)
library(gganimate)
```

```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/Users/karimia/code/basketball/NBA_SportVu")) 
```

```{r}
# source custom functions
source("_functions.R")

```
```{r}
all.movements <- read.csv("data/all.movements_0021500431.csv")

```
```{r}
head(all.movements)
```

```{r}
gameid <- "21500431"
x <- read.csv('../BasketballData/2015-16_pbp.csv')
pbp <- x[which(x$GAME_ID == "21500431"), ]
str(pbp)
```

```{r}
pbp <- pbp[-1,] #first row is NAs
colnames(pbp)[2] <- c('event.id') #will use this to merge on all.movements df
pbp0 <- pbp %>% select (event.id,EVENTMSGTYPE,EVENTMSGACTIONTYPE,SCORE)
pbp0$event.id <- as.numeric(levels(pbp0$event.id))[pbp0$event.id]
head(pbp0)
```
```{r}
all.movements <- merge(x = all.movements, y = pbp, by = "event.id", all.x = TRUE)
dim(all.movements)
```
```{r}
id303 <- all.movements[which(all.movements$event.id == 303),]
dim(id303)
head(id303)
length(table(id303$game_clock))
```


```{r}
playerdf <- player_position1(df=id303, eventid=303,gameclock=361.15)
playerdf
```
```{r}
chulldf <- chull_plot(df=id303, eventid=303, gameclock=361.15)
chulldf
```
```{r}
ballposdf <- ball_position1(df=id303, eventid=303, gameclock=361.15)
ballposdf
```
```{r}
fullcourt() + 
  geom_point(data=playerdf,aes(x=X,y=Y,group=ID,color=factor(ID)),size=6) +       #players
  geom_text(data=playerdf,aes(x=X,y=Y,group=ID,label=jersey),color='black') +     #jersey number
  geom_polygon(data=chulldf,aes(x=X,y=Y,group=ID,fill=factor(ID)),alpha = 0.2) +  #convex hull
  geom_point(data=ballposdf,aes(x=X,y=Y),color='darkorange',size=3) +             #ball
  scale_color_manual(values=c("lightsteelblue2","orangered2")) +
  scale_fill_manual(values=c("lightsteelblue2","orangered2")) +
  theme(legend.position="none")
```

```{r}
clocktimes= rev(sort(unique(id303$game_clock)))
fulldf=list()

 for(i in seq_along(clocktimes)){
  
  dplayer <- player_position1(df=id303, 303,clocktimes[i]) #Gets positions of players
  dchull <- chull_plot(df=id303, 303,clocktimes[i])       #Gets area of convex hull
  ballpos <- ball_position1(df=id303, 303,clocktimes[i])  #Gets position of ball
  dchull$jersey = "NA"
  dplayer$valx = 'player'
  dchull$valx = 'hull'
  ballpos$valx  = 'ball'
  fulldf[[i]] = rbind(dplayer,dchull,ballpos)
}

 length(fulldf)
```
```{r}
 fulldf = Map(cbind,fulldf,timebin=1:length(fulldf))  #add time unit 
table(lapply(fulldf,nrow) %>% unlist)
which(lapply(fulldf,nrow) %>% unlist   > 23)
playdf = data.table::rbindlist(fulldf)
playdf2 = playdf %>% filter(timebin!=1) %>% filter(timebin<464)
```
```{r}
fullcourt() + 
  geom_point(data=playdf2 %>% filter(valx=="player"),aes(x=X,y=Y,group=ID,color=factor(ID)),size=6) +
  geom_text(data=playdf2 %>% filter(valx=="player"),aes(x=X,y=Y,group=ID,label=jersey),color='black') +
  geom_polygon(data=playdf2 %>% filter(valx=="hull"),aes(x=X,y=Y,group=ID,fill=factor(ID)),alpha = 0.2) + 
  geom_point(data=playdf2 %>% filter(valx=="ball"),aes(x=X,y=Y),color='darkorange',size=3) +
  scale_color_manual(values=c("lightsteelblue2","orangered2")) +
  scale_fill_manual(values=c("lightsteelblue2","orangered2")) +
  theme(legend.position="none") +
  transition_manual(timebin)

#gg_animate(p, "nbaplot.gif", title_frame =F, ani.width = 600, ani.height = 450, interval=0.1)  

```


